### ISSUE TITLE
Add ability to listen to MultiFloatingActionButton state changes 

### ISSUE THREAD

**Issue by chouaibMo** [lemillion12/multi-floating-action-button#2]
Currently, the MultiFloatingActionButton composable allows users to create a multi-floating action button. However, there is no easy way for users to listen to changes in the button's state from outside the composable.

To make it easier for users to react to changes in the button's state, it would be helpful to add a callback function parameter to the MultiFloatingActionButton composable that is called whenever the button's state changes. This would allow users to listen to state changes and perform actions based on the current state of the button.

This feature would be especially useful for users who want to create more dynamic UIs with the MultiFloatingActionButton composable. For example, they could use the state changes to update other UI elements or trigger animations based on the current state of the button.

i already have an implemention idea, and i'd like to raise a PR and make it available 😉

**Comment by msanyam** [comment]
Sounds great. Can you raise the PR? I'll get it merged.

**Comment by chouaibMo** [comment]
i've made some changes and created a branch, but I don't have the necessary permissions to push my commits.    
Could you please grant me the required access to contribute? 🙏🏼

`remote: Permission to lemillion12/multi-floating-action-button.git denied to chouaibMo.`

**Comment by msanyam** [comment]
To create a pull request to the repository on GitHub, you can follow these steps:

Fork the repository: First, you need to fork the repository you want to contribute to by clicking the "Fork" button on the repository's page. This creates a copy of the repository in your own GitHub account.

Clone the repository: Once you have forked the repository, you need to clone it to your local machine using Git. You can do this by running the command git clone <forked-repository-url> in your terminal, where <forked-repository-url> is the URL of the forked repository.

Create a new branch: Before making any changes, create a new branch to work on using the command git checkout -b <new-branch-name>. This ensures that any changes you make are isolated from the main branch.

Make your changes: Now you can make the changes you want to contribute to the repository. You can edit existing files, add new files, or make any other necessary changes.

Commit your changes: Once you have made your changes, you need to commit them using the command git commit -m "<commit-message>", where <commit-message> is a brief description of the changes you made.

Push your changes: After committing your changes, you need to push them to your forked repository using the command git push origin <new-branch-name>.

Create a pull request: Finally, go to the original repository on GitHub and click the "New pull request" button. GitHub will guide you through the process of creating a pull request from your forked repository and branch to the original repository's main branch.

**Comment by chouaibMo** [comment]
Excellent, the problem is solved thank you, i've just raised the PR 😉 
(the problem is that i was trying to push a branch directly to the original repo 😅).

**Comment by msanyam** [comment]
No problem.
